<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SupportTicketSystem</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SupportTicketSystem.Domain\SupportTicketSystem.Domain.csproj" />
    <ProjectReference Include="..\SupportTicketSystem.Application.Contracts\SupportTicketSystem.Application.Contracts.csproj" />
  </ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>


	<ItemGroup>
    <PackageReference Include="Volo.Abp.Account.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="10.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="SupportTicketSystem\" />
  </ItemGroup>

</Project>
