<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SupportTicketSystem</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SupportTicketSystem.Domain\SupportTicketSystem.Domain.csproj" />
    <ProjectReference Include="..\SupportTicketSystem.TestBase\SupportTicketSystem.TestBase.csproj" />
  </ItemGroup>

</Project>
