using Xunit;

namespace SupportTicketSystem.EntityFrameworkCore;

[CollectionDefinition(SupportTicketSystemTestConsts.CollectionDefinitionName)]
public class SupportTicketSystemEntityFrameworkCoreCollection : ICollectionFixture<SupportTicketSystemEntityFrameworkCoreFixture>
{

}
