using SupportTicketSystem.EntityFrameworkCore;
using Xunit;

namespace SupportTicketSystem.EntityFrameworkCore;

public class SupportTicketSystemEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<SupportTicketSystemEntityFrameworkCoreFixture>
{

}
